/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AFI */

#ifndef _Included_AFI
#define _Included_AFI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AFI
 * Method:    AFI
 * Signature: (JJJ[F)V
 */
JNIEXPORT void JNICALL Java_AFI_AFI
  (JNIEnv *, jobject, jlong, jlong, jlong, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
